name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run example script tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          python-version: 3.12
          environment-file: environment.yml
          activate-environment: geotools-test

      - name: Install dependencies (if not using environment.yml)
        shell: bash -l {0}
        run: |
          conda env list
          conda install pytest
      
      - name: Run test
        shell: bash -l {0}
        run: |
          conda env list
          conda activate geotools-test
          python -m pytest tests/test_examples.py -q
        
